[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/datenschutz"
  to = "/datenschutz.html"
  status = 200

[[redirects]]
  from = "/impressum"
  to = "/impressum.html"
  status = 200

[[redirects]]
  from = "/leichte-sprache"
  to = "/leichte-sprache.html"
  status = 200

[[redirects]]
  from = "/pitch"
  to = "/pitch.html"
  status = 200

[[redirects]]
  from = "/spenden"
  to = "/spenden.html"
  status = 200

[[redirects]]
  from = "/newsletter"
  to = "/newsletter.html"
  status = 200

# Catch-all rule for SPA routing - must be last!
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self'"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"